### ISSUE TITLE
Error while installing adonis-bull-queue

### ISSUE THREAD

**Issue by rutonyru** [RomainLanz/adonis-bull-queue#42]
Hi Romain,

As my project becomes bigger, I need to set up bullmq (asynchrone job). I tried to install adonis-bull-queue with the command "node ace add @rlanz/bull-queue" but it failed, displaying this : 
```
[ error ] Command failed with exit code 1: npm install @rlanz/bull-queue
          at makeError (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/execa/lib/error.js:60:11)
          at handlePromise (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/execa/index.js:124:26)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async #installPackage (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/@adonisjs/core/build/commands/add.js:65:13)
          at async Add.run (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/@adonisjs/core/build/commands/add.js:112:33)
          at async Add.exec (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/@adonisjs/core/build/modules/ace/commands.js:51:28)
          at async #execMain (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/@adonisjs/ace/build/index.js:1481:7)
          at async AceProcess.handle (file:///home/aruffel/Antoine/Dev/Projets/Doc-CRG/doccrg-back-js/node_modules/@adonisjs/core/build/src/ignitor/ace.js:66:9)
```
I tried then : npm install @rlanz/bull-queue and the message is this one : 
```
[2024-06-07T13_38_22_530Z-eresolve-report.txt](https://github.com/user-attachments/files/15741153/2024-06-07T13_38_22_530Z-eresolve-report.txt)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @adonisjs/core@6.9.1
npm ERR! Found: @vinejs/vine@1.7.1
npm ERR! node_modules/@vinejs/vine
npm ERR!   @vinejs/vine@"^1.7.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @vinejs/vine@"^2.0.0" from @adonisjs/core@6.9.1
npm ERR! node_modules/@adonisjs/core
npm ERR!   @adonisjs/core@"^6.2.2" from the root project
npm ERR!   peer @adonisjs/core@"^6.2.1" from @adonisjs/auth@9.1.1
npm ERR!   node_modules/@adonisjs/auth
npm ERR!     @adonisjs/auth@"^9.1.1" from the root project
npm ERR!   10 more (@adonisjs/cors, @adonisjs/lucid, @adonisjs/mail, ...)
npm ERR! 
npm ERR! Conflicting peer dependency: @vinejs/vine@2.1.0
npm ERR! node_modules/@vinejs/vine
npm ERR!   peerOptional @vinejs/vine@"^2.0.0" from @adonisjs/core@6.9.1
npm ERR!   node_modules/@adonisjs/core
npm ERR!     @adonisjs/core@"^6.2.2" from the root project
npm ERR!     peer @adonisjs/core@"^6.2.1" from @adonisjs/auth@9.1.1
npm ERR!     node_modules/@adonisjs/auth
npm ERR!       @adonisjs/auth@"^9.1.1" from the root project
npm ERR!     10 more (@adonisjs/cors, @adonisjs/lucid, @adonisjs/mail, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/aruffel/.npm/_logs/2024-06-07T13_39_00_030Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/aruffel/.npm/_logs/2024-06-07T13_39_00_030Z-debug-0.log
```
Is it a bug ?
Thanks,
Antoine

**Comment by RomainLanz** [comment]
Hey @rutonyru! 👋🏻 

Looks like the issue is not coming from my package. Please, upgrade your `@vinejs/vine` version to fix the peer dependency issue or downgrade your `@adonisjs/core` version.

**Comment by rutonyru** [comment]
Hi @RomainLanz,
You are fantastic :) It was hard to me to understand that kind of message.
I upgrade the version of vinejs/vine to 2.0.0 and install adonis bull queue without error.
Thank you very much.
Antoine

**Comment by RomainLanz** [comment]
Nice!
